version: 2

models:
  - name: fct_apple_shop_customer_final
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: fct_apple_shop_customer_final
    tests:
      - relationships:
          to: ref('dim_customer')  # This is where the primary key is expected to be.
          field: customer_id  # This is the foreign key in your 'fct_apple_shop_customer_final' model.

  - name: another_mart_model  # This is another model in your dbt project.
    tests:
      - relationships:
          to: ref('another_dimension_model')  # This is where the primary key is expected to be.
          field: foreign_key_column  # This is the foreign key in your 'another_mart_model'.
