name: 'snowflake_workshop'
version: '1.5.1'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  snowflake_workshop:
    # Applies the following defaults to all models within the snowflake_workshop namespace
    +tests:
      - unique
      - not_null
    staging:
      materialized: view
      snowflake_warehouse: transformed
    marts:
      materialized: table
      snowflake_warehouse: transformed



